### ISSUE TITLE
No ai bots found in your spring installation

### ISSUE THREAD

**Issue by Mistwarrior** [springlobby/springlobby-website#5]
Upgrading from previous version to 0.270 gives me the message no ai bots found in your spring installation, When I attempt to play a single player game using spring lobby.  This was working correctly in previous versions.  And only happens when attempting to add bot to game.  Also i play balanced annihilation.

**Comment by abma** [comment]
https://github.com/springlobby/springlobby/blob/master/ChangeLog#L7

also, the correct bug tracker would be https://github.com/springlobby/springlobby/issues
